version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: deploy/Dockerfile
    ports:
      - 8080:80
  app:
    build:
      context: ./app
      dockerfile: deploy/Dockerfile
  redis:
    image: redis:6-alpine